name: Convert encode

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Coverting
        run: |
          cp -f ZDK_IMEdictionary.txt Google_IME.txt
          iconv -f UTF-8 -t UTF-16 ZDK_IMEdictionary.txt > MS_IME.txt
          sed s/短縮よみ/名詞/ ZDK_IMEdictionary.txt | sed '1s/^/!!ATOK_TANGO_TEXT_HEADER_1\n/' | iconv -f UTF8 -t UTF16 > ATOK.txt
          tr '\t' ',' < ZDK_IMEdictionary.txt  | tr -d '\n' > MacOS.txt
          
      
      - name: Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes" -a
          git push origin main
